=== sheremet-vlad/epam-training/task3/src/test/resources/flowers.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:tns="http://www.example.com/flowers"
        targetNamespace="http://www.example.com/flowers"
        elementFormDefault="qualified">

    <element name="flower" type="tns:Flower"/>
    <element name="carnivorous_flower" type="tns:Carnivorous_Flower" substitutionGroup="tns:flower"/>

    <element name="flowers">
        <complexType>
            <sequence>
                <element ref="tns:flower" minOccurs="2" maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <complexType name="Flower">
        <sequence>
            <element name="name" type="string"/>
            <element name="visual_parametr" type="tns:Visual_parametr"/>
        </sequence>
        <attribute name="origin" type="string"/>
        <attribute name="soil">
            <simpleType>
                <restriction base="string">
                    <enumeration value="podzolic"/>
                    <enumeration value="soddy_podzolic"/>
                    <enumeration value="unpaved"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <complexType name="Carnivorous_Flower">
        <complexContent>
            <extension base="tns:Flower">
                <sequence>
                    <element name="digestion_in_seconds" type="unsignedInt"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Visual_parametr">
        <sequence>
            <element name="stem_color" type="string"/>
            <element name="sheet_color" type="string"/>
            <element name="average_size" type="unsignedInt"/>
        </sequence>
    </complexType>
</schema>

=== sheremet-vlad/epam-training/task3/src/test/resources/flowers.xml
<?xml version="1.0" encoding="utf-8" ?>
<flowers xmlns:tns="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/flowers"
         tns:schemaLocation="http://www.example.com/flowers flowers.xsd">

    <flower origin="Russia" soil="podzolic">
        <name>Rose</name>
        <visual_parametr>
            <stem_color>Green</stem_color>
            <sheet_color>Red</sheet_color>
            <average_size>40</average_size>
        </visual_parametr>
    </flower>

    <flower origin="England" soil="soddy_podzolic">
        <name>Violet</name>
        <visual_parametr>
            <stem_color>Green</stem_color>
            <sheet_color>Yellow</sheet_color>
            <average_size>15</average_size>
        </visual_parametr>
    </flower>

    <carnivorous_flower origin="Russia" soil="podzolic">
        <name>Nepenthes</name>
        <visual_parametr>
            <stem_color>Brown</stem_color>
            <sheet_color>Green</sheet_color>
            <average_size>40</average_size>
        </visual_parametr>
        <digestion_in_seconds>654800</digestion_in_seconds>
    </carnivorous_flower>

    <carnivorous_flower origin="Russia" soil="podzolic">
        <name>Abra</name>
        <visual_parametr>
            <stem_color>Brown</stem_color>
            <sheet_color>Green</sheet_color>
            <average_size>180</average_size>
        </visual_parametr>
        <digestion_in_seconds>6500</digestion_in_seconds>
    </carnivorous_flower>
</flowers>
